# Generated by Django 4.0.6 on 2024-04-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(choices=[('instalation', 'Instação'), ('support', 'Suporte'), ('additional', 'Adicional')], max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='type',
            field=models.CharField(choices=[('weekday', 'Padrão'), ('sunday_holiday', 'Domingo/Feriado'), ('night', 'Noturno')], max_length=20),
        ),
    ]
