# Generated by Django 4.0.6 on 2024-04-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_jobpost_amount_alter_jobpost_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
