# Generated by Django 4.0.6 on 2024-04-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('weekday', 'Normal Weekday'), ('sunday_holiday', 'Sunday/Bank Holiday'), ('night', 'Night Time')], max_length=20)),
                ('date', models.DateField()),
                ('WO', models.CharField(max_length=20)),
            ],
        ),
    ]
